### ISSUE TITLE
Implement the dark colour scheme

### ISSUE THREAD

**Issue by n-maido** [SiddeshSambasivam/DataAnnotated#10]
### Colour Palette
![AdobeColor-My Color Theme](https://user-images.githubusercontent.com/58193906/108299719-c5d18900-7153-11eb-920d-1a5418ad6479.jpeg)

### Colour Guide
Blues -> Backgrounds, Cards
Orange(s) -> Icons, Buttons
Light Gray -> Text

**Comment by SiddeshSambasivam** [comment]
Bg-Primary: #02020D
Bg-Secondary: #05031F
Pop collor: #ff8a00
Text Primary: #eeeeee
